### ISSUE TITLE
Create schemas

### ISSUE THREAD

**Issue by Astatium5** [COP4331-Large-Project/server#7]

**Comment by Armintron** [comment]
Can you give more detail on what this issue pertains to? Is it `Schema` objects used when creating a `mongoose.model` or a general schema for the database structure?

Also, if it pertains to the first one, why should we create schemas and not their respective models? I dont see a case where we need to export the scheme and then manually call `mongoose.model` on it when using it.

**Comment by Astatium5** [comment]
> Can you give more detail on what this issue pertains to? Is it `Schema` objects used when creating a `mongoose.model` or a general schema for the database structure?
> 
> Also, if it pertains to the first one, why should we create schemas and not their respective models? I dont see a case where we need to export the scheme and then manually call `mongoose.model` on it when using it.

It's about documentation schemas. They will be stored in the schemas.yml file.

**Comment by suneettipirneni** [comment]
> > Can you give more detail on what this issue pertains to? Is it `Schema` objects used when creating a `mongoose.model` or a general schema for the database structure?
> 
> > 
> 
> > Also, if it pertains to the first one, why should we create schemas and not their respective models? I dont see a case where we need to export the scheme and then manually call `mongoose.model` on it when using it.
> 
> 
> 
> It's about documentation schemas. They will be stored in the schemas.yml file.

I think if that's the case this issue should be renamed to something like "create schema docs" so it doesn't cause confusion.

**Comment by Astatium5** [comment]
> > > Can you give more detail on what this issue pertains to? Is it `Schema` objects used when creating a `mongoose.model` or a general schema for the database structure?
> > 
> > 
> > > 
> > 
> > 
> > > Also, if it pertains to the first one, why should we create schemas and not their respective models? I dont see a case where we need to export the scheme and then manually call `mongoose.model` on it when using it.
> > 
> > 
> > It's about documentation schemas. They will be stored in the schemas.yml file.
> 
> I think if that's the case this issue should be renamed to something like "create schema docs" so it doesn't cause confusion.

I think it has already created some confusion for me, because the Swagger schemas were included to the Swagger issue. I think in this case I meant models by schemas. And yes, that's what Armin showed in his link.
